[env:esp32-s3]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.f_cpu = 240000000L 
board_build.arduino.memory_type = qio_opi

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    https://github.com/Bodmer/U8g2_for_TFT_eSPI.git
    h2zero/NimBLE-Arduino@^1.4.1
build_flags =
    -I src/hal
    -I src/sys
    -I src/apps
    -I src/assets
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    
    ; 【关键补丁 1】：修复色彩反转（如果改完颜色还是不对，就把 ON 改成 OFF）
    -D TFT_INVERSION_OFF=1
    ; 【关键补丁 2】：修复 240x240 屏幕的内存偏移（错位问题）
    -D CGRAM_OFFSET=1
    
    ; --- 沉冤得雪的原版硬件加速引脚 ---
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=9
    -D TFT_RST=14
    
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1

    ; 【关键补丁 3】：降频到 40MHz，彻底解决杜邦线干扰导致的“突然黑屏休眠”！
    -D SPI_FREQUENCY=27000000