[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
board_build.f_cpu = 160000000L
framework = arduino
monitor_speed = 115200 
lib_deps = 
    bodmer/TFT_eSPI @ ^2.5.31

build_flags =
    -D USER_SETUP_LOADED=1
    
    ; 【核心修复】：将驱动换成 ST7789
    -D ST7789_DRIVER=1
    
    ; 【核心修复】：将分辨率改为正方形的 240x240
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    
    ; 引脚连线保持完美，完全不用动！
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D SPI_FREQUENCY=40000000 ; ST7789 性能更强，我们把 SPI 频率拉高到 40MHz！