#include "prescript_data.h"

static const char* prescripts[] = {
    "FIND ISHMAEL.",
    "KILL YOUR PAINTING.",
    "CLEAR.",
    "I'M BURGER.",
    "STARE AT A CORNER FOR EXACTLY 300 SECONDS.",    
    "TEAR A BLANK PAGE INTO EXACTLY 17 PIECES.",     
    "WHISPER 'YES' TO THE NEXT PERSON WHO SPEAKS.",  
    "CARVE A SMILE INTO A RUBBER BLOCK AND BURN IT.",
    "CARVE THE EXACT SHAPE OF YOUR THUMBPRINT ONTO A FRESH RUBBER BLOCK. ONCE COMPLETED, COAT IT WITH BLACK INK AND STAMP IT ON THE NEAREST CONCRETE WALL UNTIL THE INK RUNS DRY.",
    "CUT THE RED WIRE. LEAVE THE BLUE WIRE.",
    "SOLDER EXACTLY 14 COPPER WIRES INTO A PERFECT WEB. CONNECT THE CENTER TO GROUND, AND LET THE ENDS HANG LOOSE. LISTEN TO THE STATIC UNTIL IT SOUNDS LIKE A VOICE."
};

static const int PRESCRIPT_COUNT = sizeof(prescripts) / sizeof(prescripts[0]);

int Get_Prescript_Count() { return PRESCRIPT_COUNT; }
const char* Get_Prescript(int index) { return prescripts[index]; }